name: img

services:
  - name: browser
    dockerfile_path: .do/Dockerfile.browser
    github:
      repo: phuctm97/img-node
      branch: master
    internal_ports:
      - 3000
  - name: api
    environment_slug: node-js
    github:
      repo: phuctm97/img-node
      branch: master
    envs:
      - key: BROWSER_ENDPOINT
        scope: RUN_TIME
        value: "${browser.PRIVATE_DOMAIN}:3000"
